### ISSUE TITLE
Facebook failed

### ISSUE THREAD

**Issue by alexanderisora** [bodrovis/Sitepoint-source#15]
When I click "Facebook" nothing happens. Thanks for your time.

**Comment by bodrovis** [comment]
@alexanderisora I presume you are talking about this article https://www.sitepoint.com/rails-authentication-oauth-2-0-omniauth/ ? I have lots of them and the "contributing" guide is there for a good reason :) https://github.com/bodrovis/Sitepoint-source/blob/master/CONTRIBUTING.md

My guess is that Facebook API has changed since I wrote this article, so the gems should be updated.

**Comment by alexanderisora** [comment]
Thanks for your reply @bodrovis

**Comment by bodrovis** [comment]
This should fix it. Please let me know if you still cannot log in!

**Comment by alexanderisora** [comment]
@bodrovis works great now!
