### ISSUE TITLE
Steam-Powered DOTA demo is not working

### ISSUE THREAD

**Issue by maksimf** [bodrovis/Sitepoint-source#2]
After signing up via Steam I get 500 error.

**Comment by bodrovis** [comment]
Yeah, I've seen this error when my friend was testing the app. The basic idea is that Steam API sometimes may not respond properly and return empty array instead (it has some other nasty issues like not following naming conditions of its methods). Probably I'll just go ahead and check for empty arrays everywhere in the loaders... If you tell me your steam id I'll just delete those partially loaded matches from the table and you may try again :)

**Comment by maksimf** [comment]
Here it is: http://steamcommunity.com/profiles/76561197984638048/

**Comment by bodrovis** [comment]
Okay, I've destroyed everything but the last match that seems to be okay. Looking into this issue, there is a strange error probably related to items...

**Comment by maksimf** [comment]
Should I try to log in now?

**Comment by bodrovis** [comment]
Yep, go ahead :)

**Comment by maksimf** [comment]
Still 500, unfortunately

**Comment by bodrovis** [comment]
Okay, I've found the issue and this time it has nothing to do with Steam API. http://www.dotabuff.com/matches/1476199242 here is your match that had problems. This is because you've bought a new artifact that `dota` gem has no idea of :) This gem maintains a local copy of some data (https://github.com/bodrovis/dota/tree/master/data) and so when parsing items here https://github.com/bodrovis/Sitepoint-source/blob/master/Dota_on_Rails/app/models/match.rb#L29 an error is throwed. I'll send PR to support new items, hopefully today.

**Comment by maksimf** [comment]
Thanks! :)

**Comment by bodrovis** [comment]
Okay, PR is sent - for now I'm just referencing directly to the branch inside my forked repo. Things should be okay now!
