### ISSUE TITLE
load_matches! error

### ISSUE THREAD

**Issue by Igorpollo** [bodrovis/Sitepoint-source#6]
Hi.
I just found this code. Is awesome.
But, the live example is not working. I've cloned the repository and isn't working too.
I'm getting this error:

Faraday::ParsingError at /auth/steam/callback
757: unexpected token at '<html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>'
the error show the "load_matches!" action.
The token is right.
Can u help me?

**Comment by bodrovis** [comment]
What app are we talking about? Please refer to this doc https://github.com/bodrovis/Sitepoint-source/blob/master/CONTRIBUTING.md and provide some additional info.

**Comment by bodrovis** [comment]
If you are talking about Dota, then it is required to have local_env.yml file inside config, as it is being loaded: https://github.com/bodrovis/Sitepoint-source/blob/master/Dota_on_Rails/config/application.rb#L35 Inside provide your Steam API key. I excluded my own key from version control due to privacy reasons. Inside local_env.yml place

``` yaml
STEAM_KEY: 'your_key'
```

If it does not help please provide more info.

**Comment by Igorpollo** [comment]
Yes, it's dota.
I've created the file and the erro is the same:
`Faraday::ParsingError at /auth/steam/callback
757: unexpected token at '<html><head><title>Forbidden</title></head><body><h1>Forbidden</h1>Access is denied. Retrying will not help. Please verify your <pre>key=</pre> parameter.</body></html>'`

Showing this line:
`matches_arr = Dota.api.matches(player_id: self.uid, limit: count)`

In adition of this file `local_env.yml` i have in*\* secrets.yml*\* my key:
`STEAM_WEB_API_KEY: 0F0A970096FCE4611F9326xxxxxxxx`
And in*\* initializers/omniauth.rb*\* I have this:
`Rails.application.config.middleware.use OmniAuth::Builder do
  provider :steam, Rails.application.secrets.STEAM_WEB_API_KEY
end
`
If I remove the action `load_matches!` the login via omniauth works fine.
Thanks

**Comment by bodrovis** [comment]
`Rails.application.secrets.STEAM_WEB_API_KEY` should be `ENV['STEAM_WEB_API_KEY']` if you use local_env.yml. You can use any other method of storing private keys, like figaro gem. 

If that does not help, then you'll probably should google for it because maybe Dota api has changed and now requires additional permissions...
